spring:
  datasource:
    schema: import.sql
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.ko.mybatis.domain
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: true
  before: true
  mappers: tk.mybatis.mapper.common.Mapper