# DataSource Config
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://gpdb.rds.aliyuncs.com:3432/greenplum
    username:
    password:

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
