server.port: 1337

spring:
  application.name: ko-generator
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.224.68:3306/art-prototype?useUnicode=true&characterEncoding=utf-8&useSSL=false
    name: art-prototype
    username: root
    password: tiger

generator:
  moduleName: case-generator
  tables: art_link
  enable: false   #开启后生成全库

rootPackage: org.ko.generator
xmlPackage: mappers

java.enable: true #开启后生成后台代码

view:
  filePath: D://
  enable: true    #开启后生成前台代码
  js:
  html:

copyProject:
  name: project-name
  path: D://
  enable: false
