spring:
  application.name: ko-generator
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tiger
    url: jdbc:mysql://111.231.224.68:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false
  session:
    store-type: none #取消spring session管理


server:
  port: 8010

#security:
#  basic:
#    enabled: false #关掉security boot 默认配置


#ko.security.browser.loginPage: /ko-login.html
#ko.security.browser.loginType: REDIRECT
#ko.security.code.image.length: 6
#ko.security.code.image.width: 100
#ko.security.code.image.url: /user, /user/*
ko.seucrity.social.qq.app-id:
ko.seucrity.social.qq.app-secret:
ko.security.browser.loginPage: /signUp.html
